Fix error C3861: 'usleep': identifier not found on Windows (#2383)
* Fix error C3861: 'usleep': identifier not found on Windows

* Fixup

(cherry picked from commit 80a5f3e17363f3a6a8419f71b5a0b53cde83672d)